version: "3.9"
services:
  bitcoind:
    image: ruimarinho/bitcoin-core:23.0-alpine
    command:
      -printtoconsole
      -regtest=1
      -server=1
      -fallbackfee=0.00001
      -rpcbind=0.0.0.0:8332
      -rpcport=8332
      -rpcuser=user
      -rpcpassword=password
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:3010
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo"]
    ports:
      - "8332:8332"
    volumes:
      - bitcoin-data:/data
    networks:
      - bitcoin
  bitcoin-cli:
    image: nicolasdorier/docker-bitcoin:22.0
    entrypoint: ["/entrypoint.sh", "bitcoin-cli"]
    command: "-rpcuser=user -rpcpassword=password"
    depends_on:
      - bitcoind
    network_mode: service:bitcoind

networks:
  bitcoin:

volumes:
  bitcoin-data: